name: Release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  Test:
    name: Unit tests with coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up Go 1.25
        uses: actions/setup-go@v6
        with:
          go-version: 1.25
      - run: go mod download
      - run: go vet ./...

      - name: Running go tests with coverage
        env:
          GO111MODULE: on
        run: make cover
      - name: Send coverage
        uses: coverallsapp/github-action@v2
        with:
          file: ./coverage.out

  GolangLint:
    name: Golang Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up Go 1.25
        uses: actions/setup-go@v6
        with:
          go-version: 1.25
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.6
  
  Release:
    runs-on: ubuntu-latest
    needs: [Test, GolangLint]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up Go 1.25
        uses: actions/setup-go@v6
        with:
          go-version: 1.25
      - name: Get version
        run: |
          go generate ./pkg/version > version.txt
          echo "df_version=$(cat version.txt | grep releaseVersion | cut -d ':' -f 2 | awk '$1=$1')" >> $GITHUB_OUTPUT
          rm version.txt
      - name: Check Formal Version
        id: check_formal_version
        run: |
          VERSION_PATTERN="^[0-9]+\.[0-9]+\.[0-9]+$"
          if [[ "${{ steps.get_version.outputs.df_version }}" =~ ${VERSION_PATTERN} ]]; then
            echo "is_formal_version=true" >> $GITHUB_OUTPUT
            echo "Release a formal version!"
          else
            echo "is_formal_version=false" >> $GITHUB_OUTPUT
            echo "Release an informal version!" 
          fi
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Informal Release
        if: ${{ steps.check_formal_version.outputs.is_formal_version == 'false' }}
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --config .goreleaser_informal.yaml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.A1Y_BOT_TOKEN }}
          DF_VERSION: ${{ steps.get_version.outputs.df_version }}

      - name: Run Formal Release
        if: ${{ steps.check_formal_version.outputs.is_formal_version == 'true' }}
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --config .goreleaser.yaml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.A1Y_BOT_TOKEN }}
          DF_VERSION: ${{ steps.get_version.outputs.df_version }}
